#ifndef _COSMIC_ERROR_H
#define _COSMIC_ERROR_H

/*
 * Todo list
 * - [ ] PWM error codes
 */

typedef enum {
    OK,
    GPIO_PIN_TOO_HIGH,
    GPIO_ALTERNATE_FUNC_TOO_HIGH,
    GPIO_ALTERNATE_NOT_SELECTED,
    GPIO_INVALID_SETTING,
    USART_ERR_UNDEFINED,        /*!< USART port undefined (NULL) */
    USART_ERR_IT_BUF_FULL,      /*!< USART full interrupt mode buffer */
    USART_ERR_RX_EMPTY,
    I2C_ERR_PORT_NOT_AVAILABLE,
    I2C_ERR_FREQ_TOO_LOW,
    I2C_ERR_FREQ_TOO_HIGH,
    I2C_ERR_BUS,
    I2C_ERR_ARBLOSS,
    I2C_ERR_AF,
    I2C_ERR_OVR,
    I2C_ERR_PEC,
    I2C_ERR_TIMEOUT,
    I2C_ERR_SMBALERT,
    I2C_ERR_PORT_UNDEFINED,
    I2C_ERR_NOT_CONFIGURED,
    I2C_ERR_BUS_TIMEOUT,
    TIM_ERR_CONFIG_NO_TIMER,
    TIM_ERR_CONFIG_PRESCALER_OVERFLOW,
    TIM_ERR_CONFIG_PRESCALER_ZERO,
    TIM_ERR_CONFIG_AUTORELOAD,
    EXTI_LINES_RESERVED,
    EXTI_PIN_TOO_HIGH, 
	ADC_ERR_PIN_NOT_ADC,
	ADC_ERR_WRONG_MODE,
	ADC_ERR_WRONG_RESOLUTION,
	ADC_ERR_PORT_ALREADY_INIT,
	ADC_ERR_NO_FREE_CHANNEL,
} error;

#endif
